spring:
  application:
    name: gatewary
  cloud:
    gateway:
      #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由, 下面根据先后顺序转发
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
#              - Path=/zzzgd/** # 请求地址携带zzzgd的,则转发
#              - Header=X-Request-Id, \d+
              - After=2020-01-20T17:42:47.789-07:00[America/Denver]
        
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka.didispace.com/eureka/
#  instance:
#    lease-expiration-duration-in-seconds: 3
#    lease-renewal-interval-in-seconds: 2
server:
  port: 8765